### ISSUE TITLE
Plugin don´t work

### ISSUE THREAD

**Issue by PuschiYT** [Trojaner25/Rocket-Regions#102]
I have downloaded the plugin and unzipped then I have done it in the plugins folder reinstalled the server and then I went ingame when I wanted to select you region and / rpos1 geamcht was in the chat "Command not Found" please Help me with this problem
best regards
Puschi

**Comment by Trojaner** [comment]
Download the plugin from https://github.com/Trojaner/Rocket-Regions/releases
