### ISSUE TITLE
Plugin Rocket-Regions v1.5.0.0 not loading

### ISSUE THREAD

**Issue by EliteMuffin** [Trojaner25/Rocket-Regions#103]
I downloaded Rocket-Regions v1.5.0.0 from this github and I put the dll in my rocket plugins under my server and I launch the server and it spams my console with "[2019-03-16 20:20:20]: TypeLoadException: Could not load type 'System.Func`2' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. -" Any help?

**Comment by Trojaner** [comment]
1.5.0.0 requires .NET 4.6 you are running on .NET 3.5.

**Comment by EliteMuffin** [comment]
How do i put .NET 4.6 on an unturned server?
