### ISSUE TITLE
This plugin does not work with my server

### ISSUE THREAD

**Issue by EliteMuffin** [Trojaner25/Rocket-Regions#104]
The plugin simply doesn't load. It just crashes the server causing me to delete the plugin and start again, wasting time. I believe that version v1.5.0.0 needs .NET 4.5 but I don't see how I can fix this issue seeing as my service provider is hosted on Linux. And I cannot update the .NET version. If there is a working version that I could use or a way to fix this one please respond to me with useful information, thanks!

**Comment by Trojaner** [comment]
Read the other issues.
