### ISSUE TITLE
@Trojaner

### ISSUE THREAD

**Issue by EliteMuffin** [Trojaner25/Rocket-Regions#105]
Please take a look at this video. I looked at the previous issues and all I was able to find was download it from GitHub which I've been doing. Is there a fix for this issue?

https://youtu.be/ZWYArfERArU

**Comment by Trojaner** [comment]
Your hoster is using Linux with .NET 3.5, this is not supported anymore.
Migrate to a proper hoster which uses Windows.

EliteMuffin <notifications@github.com> schrieb am Fr., 22. März 2019, 03:41:
