### ISSUE TITLE
Failed to load RocketRegions

### ISSUE THREAD

**Issue by IcedHost** [Trojaner25/Rocket-Regions#110]
Dear Trojaner,

I am the owner of IcedHost, a game server hosting company.
I've some clients running on Rocketmod Unturned and they are having some issues related to Rocker-Regions.

Whenever they startup their server, it's giving the following error:

```
Failed to load RocketRegions, unloading now... :System.TypeLoadException: Could not load type '<>c' from assembly 'RocketRegions, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
at Rocket.Core.Plugins.RocketPlugin.LoadPlugin () [0x00000] in <filename unknown>:0
[unloading] RocketRegions
Failed to unload RocketRegions:System.TypeLoadException: Could not load type '<>c' from assembly 'RocketRegions, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
at Rocket.Core.Plugins.RocketPlugin.UnloadPlugin (PluginState state) [0x00000] in <filename unknown>:0
at Rocket.Core.Plugins.RocketPlugin.LoadPlugin () [0x00000] in <filename unknown>:0


```
Then after a short period of time, it's displaying the following error each few seconds:

```[TypeLoadException: Could not load type 'System.Func`2' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. -]```

I hope we can resolve this issue together.

Greets,

Thijs
www.icedhost.net

**Comment by Trojaner** [comment]
Your clients are using the .NET 4.6.1 Version of RocketRegions (>= 1.5.0.0). Unturned Linux 32bit build still uses .NET 3.5.
Either upgrade to using the 64bit Linux Unturned build (which uses .NET 4.6.1) or tell your clients to use the older Regions version 1.4.0.0, which still supports .NET 3.5.

In general I would suggest you to upgrade to the 64bit Linux server instead, as new and updated plugins nowadays do not support .NET 3.5 anymore.
