### ISSUE TITLE
Cannot create zone

### ISSUE THREAD

**Issue by Nicholaiii** [Trojaner25/Rocket-Regions#2]
```
[Error] An error occured while executing command /screate newpos:        System.NullReferenceException: Object reference not set to an instance of an object
  at Safezone.Commands.CreateCommand.Execute (Rocket.Unturned.Player.RocketPlayer caller, System.String[] command) [0x00000] in <filename unknown>:0 
  at Rocket.Unturned.Commands.RocketAliasBase.execute (CSteamID caller, System.String command) [0x00000] in <filename unknown>:0 
```

Most recent build as of writing. 
Also unrelated note, but upon first execution the whole server was treated as safezone, this was not the case in subsequent runs

**Comment by Trojaner** [comment]
Thanks, I recently made some untested changes.

I will look into that

**Comment by Trojaner** [comment]
Can you please test it again with the latest commit?

**Comment by Nicholaiii** [comment]
Builds fine, cannot figure out what type to use. Tried literally anything the source would point me to. Outputs nothing as available types.

**Comment by Nicholaiii** [comment]
![image of output](http://puu.sh/iMiv8/43c98754df.jpg)

**Comment by Trojaner** [comment]
Thanks, I know what caused it.

will fix it soon

**Comment by Trojaner** [comment]
Does it work now?

**Comment by Nicholaiii** [comment]
![Image of error](http://puu.sh/iMVYG/80f3e167ad.png)

Nope!

**Comment by Trojaner** [comment]
Hmm.. I will look into that tomorrow

**Comment by Trojaner** [comment]
Fixed it, can you please test it?

**Comment by Solenus** [comment]
I'm getting this:

```
Loading SafeZonePlugin 1.0.0.0..................................................

     Loading 0 translations
     Loading 0 RocketPlayerComponents
     + /coords - Shows your current position
     + /safezonecreate - Create a safezone
         Alias: /screate
     + /safezoneinfo - Show license info and link to source code of the SafeZone
 Plugin
         Alias: /sinfo
     + /safezonelist - List all safezones
         Alias: /slist
     + /safezonepos1 - Set first positon for safezones
         Alias: /spos1
     + /safezonepos2 - Set second positon for safezones
         Alias: /spos2
     + /safezoneredefine - Redefine a safezone
         Alias: /sredefine
     + /safezoneremove - Remove a safezone
         Alias: /sremove
Failed to load Rocket_Safezone, unloading now... :System.ArgumentException: Rect
angleType is not a SafeZoneType!
  at Safezone.Model.SafeZoneType.RegisterSafeZoneType (System.String name, Syste
m.Type t) [0x00000] in <filename unknown>:0
  at Safezone.SafeZonePlugin.Load () [0x00000] in <filename unknown>:0
  at Rocket.Unturned.Plugins.RocketPlugin.LoadPlugin () [0x00000] in <filename u
nknown>:0
```

**Comment by Nicholaiii** [comment]
I got the same errors. So...

I changed

```
if(typeof(SafeZoneType).IsAssignableFrom(t))
 {
 throw new ArgumentException(t.Name + " is not a SafeZoneType!");
 }
```

Into

```
if(!typeof(SafeZoneType).IsAssignableFrom(t))
 {
 throw new ArgumentException(t.Name + " is not a SafeZoneType!");
 }
```

Since I assumed you wanted to throw the exception if it wasnt assignable, and I can then successfully load and run and create zones, however, the new flag system throws exceptions like it's the end of the world:
![Exception Hell](http://puu.sh/iSDdK/3b180b07f2.png)

These happen at every PlayerUpdatePosition event that happens inside of the Safezone area.

Also when inputting, say, eg
/screate rectangle test
the area will be named rectangle, not test. 

When listing the types in-game, it outputs ", circle" - however, circle registers as an invalid type when trying to create one.

**Comment by Trojaner** [comment]
Ok, thanks for the bug list. It won't take long to fix them

**Comment by Trojaner** [comment]
How about now?

Flags should work now, fixed (again) the wrong if statement for SafeZoneTypes and fixed the names.

Still don't know why circles don't work...

**Comment by Nicholaiii** [comment]
Safezones of rectangle types work partially now. I have to restart the server because it will still give me diarrhetic exception hell on player events, but those are gone after the restart.

When looking in the console the errors are related to flags, and when looking in the Rocket_Safezone.config.xml, the old zone has "      <Flags />" but the new one does not.
![EXCEPTION CHAOS](http://puu.sh/iSYRH/fd3be49654.png)

**Comment by Trojaner** [comment]
Did you reset the config when you updated?
Older zones may now be incompatible.

**Comment by Nicholaiii** [comment]
Yes, I did. Also, some portion got lost between the quotation marks. I was meant to type `<Flags />`
Edit: So, that means the old zone (after update and after server restart) had the empty flag tag in the config, but the new one did not.

Which also brings me to the next question, maybe some default flags untill you implement /sflag - i was just thinking godmode and nozombie.

**Comment by Trojaner** [comment]
I will implement /sflag today or tomorrow

**Comment by Trojaner** [comment]
Can you please test it again? Thanks

**Comment by Nicholaiii** [comment]
```
Failed to load Rocket_Safezone, unloading now... :System.ArgumentException: Rect
angleType is not a SafeZoneType!
  at Safezone.Model.SafeZoneType.RegisterSafeZoneType (System.String name, Syste
m.Type t) [0x00000] in <filename unknown>:0
  at Safezone.SafeZonePlugin.Load () [0x00000] in <filename unknown>:0
  at Rocket.Unturned.Plugins.RocketPlugin.LoadPlugin () [0x00000] in <filename u
nknown>:0
```

Deleted config, restarted, no change.
Checked source, found this:

```
            if(!t.IsSameOrSubclass(typeof(Flag.Flag)))
            {
                throw new ArgumentException(t.Name + " is not a SafeZoneType!");
            }
```

Did you actually want to check it the given SafeZoneType is a Flag type?

**Comment by Nicholaiii** [comment]
After changing the source code to 

```
            if(!t.IsSameOrSubclass(typeof(SafeZoneType)))
            {
                throw new ArgumentException(t.Name + " is not a SafeZoneType!");
            }
```

I can create the SafeZones again, but I still get the exception mess as earlier before restarting. Whenever I add a flag, I will get the error that "testarea" is not a flag, or "godmode" is not a safezone, regardless of how I position it. (thats both `/sflag testarea godmode 1/on/true` or `/sflag godmode testarea 1/on/true`)

**Comment by Trojaner** [comment]
> if(!t.IsSameOrSubclass(typeof(Flag.Flag)))

Oh, that happens if you copy & paste :D

 Apparently only the error message for /sflag was wrong. It still checks for "godmode" if you flag the area "testarea" with `/sflag testarea godmode < value >`.

However, it still didn't work because of wrong case checking. "Godmode" wasn't equal "godmode".

Please try it again, I fixed these errors.

**Comment by Nicholaiii** [comment]
he, yeah, copy paste, worst best thing to happen.

I get this upon trying to set a flag:
![Flag errors](http://puu.sh/iY9hC/14a3a644fa.png)

And still when entering/exiting the zones I get the crazy flood of exceptions, only this time, a restart wont remove them.

**Comment by Nicholaiii** [comment]
This is the error on PlayerUpdatePosition:

```
Error in Event PlayerUpdatePosition: System.Reflection.TargetInvocationException
: Exception has been thrown by the target of an invocation. ---> System.InvalidO
perationException: Can't cast Boolean to Boolean
  at Safezone.Model.Flag.Flag.GetValue[Boolean] () [0x00000] in <filename unknow
n>:0
  at Safezone.SafeZonePlugin.OnPlayerUpdatePosition (Rocket.Unturned.Player.Rock
etPlayer player, Vector3 position) [0x00000] in <filename unknown>:0
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (ob
ject,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invoke
Attr, System.Reflection.Binder binder, System.Object[] parameters, System.Global
ization.CultureInfo culture) [0x00000] in <filename unknown>:0
  --- End of inner exception stack trace ---
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invoke
Attr, System.Reflection.Binder binder, System.Object[] parameters, System.Global
ization.CultureInfo culture) [0x00000] in <filename unknown>:0
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] par
ameters) [0x00000] in <filename unknown>:0
  at System.Delegate.DynamicInvokeImpl (System.Object[] args) [0x00000] in <file
name unknown>:0
  at System.MulticastDelegate.DynamicInvokeImpl (System.Object[] args) [0x00000]
 in <filename unknown>:0
  at System.Delegate.DynamicInvoke (System.Object[] args) [0x00000] in <filename
 unknown>:0
  at Rocket.Core.Events.RocketEvents.TryTrigger[PlayerUpdatePosition] (System.Mu
lticastDelegate theDelegate, System.Object[] args) [0x00000] in <filename unknow
n>:0
```

**Comment by Trojaner** [comment]
Ok...fixed too..(and made some changes to xml which aren't backwards compatible)
Does it work now?

**Comment by Trojaner** [comment]
@Nicholaiii

**Comment by Nicholaiii** [comment]
Sorry, I made some tests and initially it didn't work. Let me get back to you later this evening mans! :)

(I always delete conf every time i compile the plugin btw)

**Comment by Trojaner** [comment]
Ok, thanks :+1:
