### ISSUE TITLE
New Error Version 29.06.2016

### ISSUE THREAD

**Issue by jorea143** [Trojaner25/Rocket-Regions#22]
Sorry to keep sending error messages reports. I only intend to make your plugin work properly since I really like your idea. Here's what I am getting using latest plugin and rocket version.

[http://pastebin.com/raw/bYB2gp8b](http://pastebin.com/raw/bYB2gp8b)

**Comment by Trojaner** [comment]
Please dont stop sending error reports, I need as many of them as possible.

Please send me your safezone configuration.

**Comment by jorea143** [comment]
here it is. The error disappeared once I deleted the config file---FYI.

[http://pastebin.com/raw/PbnMxxgM](http://pastebin.com/raw/PbnMxxgM)

**Comment by Trojaner** [comment]
Has been fixed.
