### ISSUE TITLE
Bug(s) with the latest update: 29.06.2016

### ISSUE THREAD

**Issue by Honcho11** [Trojaner25/Rocket-Regions#23]
Hello I used this plugin on my server I will talk about the bugs I have encountered.
- [x] 1. When Using NoZombies Flag they will become invisible.
- [x] 2. I Do not know if this is a bug but Godmode Is not constant like if an admin had it. for example if I shot someone if a room with god mode they have to exit then enter the room.
- [x]  3. With NoEnter or NoLeave people will be teleported to the roof of the map and stay there until someone makes the flag False.
  Thats all I have found for now. ~Honcho

**Comment by Trojaner** [comment]
1. Should be fixed, needs testing. 
2. This seems to be a rocket thing, not much I can do there.
3. Has been also fixed.

**Comment by Honcho11** [comment]
Ok thanks!

**Comment by Trojaner** [comment]
Godmode should work now as expected

**Comment by Honcho11** [comment]
You're a god!!!
