### ISSUE TITLE
/Sflags breaks safezones

### ISSUE THREAD

**Issue by TheRealZxc** [Trojaner25/Rocket-Regions#24]
EnterVehiclesAllowed does not work at all. command does nothing as if it doesn't exist

Godmode breaks safezone upon resarting server

nozombies breaks safezone upon restart

noplace doesn't work either

**Comment by Trojaner** [comment]
Ok. I will look into this later (I dont have much time this week)

**Comment by Honcho11** [comment]
I have the same problems and thank helping me find out why my safe zone just disappeared.And Also NoZombies makes Zombies invisible and NoEnter/NoLeave makes Players just TP to the roof :/
