### ISSUE TITLE
DestroyAllowed issue

### ISSUE THREAD

**Issue by sharkbound** [Trojaner25/Rocket-Regions#28]
if a weapon deals more damage than the structure/barricades health it will still be destroyed even with the destroyallowed flag set to false

**Comment by Trojaner** [comment]
The plugin sets the health of structures and barricades to ~65535 (for comparison, a rocket launcher deals only 1000 damage), it also instantly heals them when their health goes lower.  

Which version of the plugin did you use?
Which object did you try to destory?

On my local server I was not able to destroy sandbags with rocket launchers when this flag was set to false. However, when it was set to true, the sandbags instanly got destroyed.

**Comment by sharkbound** [comment]
Which version of the plugin did you use? Latest under downloads page
Which object did you try to destory? sandbag
i tested it again and it still destroys it with the flag set to false, but whats interesting is that if i shoot the sandbag with a gun then hit it with a tank cannon it usually takes 1 tank cannon hit then the next destroys it.

here is the plugin config if its any useful -  http://pastebin.com/sd7pQFSA

Edit 1: i did /sflag t destroyallowed false, just incase it help
Edit 2: after test a bunch more it seems more or less random if it destroys from the tank or not. I had it not destroy after taking 6 shots then after 6'th shot it destroyed, Also im using latest rocket version

**Comment by Trojaner** [comment]
Fixed (see #31)
