### ISSUE TITLE
DestroyAllowed does not work with all structures

### ISSUE THREAD

**Issue by Trojaner** [Trojaner25/Rocket-Regions#31]
Reports suggest that this flag is not working on wooden structures, glass etc. Maybe the flag isnt working at all and people just can't destroy metal structures...

**Comment by sharkbound** [comment]
this is just a guess but could this bit of code be the issue?

```
else if (structure.structure.health > asset.health)
                        {
                            structure.structure.health = asset.health;
                        }
```

**Comment by Trojaner** [comment]
The code part you posted is for resetting the health when DestroyAllowed has been set to true
