### ISSUE TITLE
Problem with update 16.07.2016

### ISSUE THREAD

**Issue by Honcho11** [Trojaner25/Rocket-Regions#35]
I am a running a server on a workshop map maybe thats why this is happening I'm running Greenport Island my base is on  a hill maybe thats why as well but when i create a region. with [/rpos 1 & 2] i create it. It creates a region but only certain spots get a safe zone when in my base it says left and entered while inside when I wanted the whole base to be covered.

**Comment by Trojaner** [comment]
Use /rcreate <name> circle <radius> instead, its easier.
