### ISSUE TITLE
Groups Still not working for me

### ISSUE THREAD

**Issue by MarcAppledash** [Trojaner25/Rocket-Regions#47]
If i try to make a Region so that only member can go in it .It wont let anyone in the zone. I used /rflag "....." noenter true -g NONMEMBER

but it dont work. I tryed it with /rflag "...." noenter true nonmember but it still sayes:

"Flag has been set to:flase for group ALL"

Please try to fix this Problem

If anyone else have the same problem

**Comment by Trojaner** [comment]
I will look into this, thank you for the bug report.

**Comment by MarcAppledash** [comment]
Np Keep it up
