### ISSUE TITLE
Cannot create a region

### ISSUE THREAD

**Issue by James76931** [Trojaner25/Rocket-Regions#49]
Hi,

I'm trying out your Regions plugin but I'm running into a bit of an issue.

I try to do /rpos1 at one corner of an area and /rpos2 at the opposite, but they give no output in chat to say that the corners were defined and then when I try to create it I am told that I need to do /spos1 and /spos2 instead and that the region couldn't be created...

The issue with /spos1 and /spos2 is that they instead of giving no output in chat say that the commands don't exist. Even when typing those two commands in and trying to create the region afterwards won't work.

If you could fix this that would be awesome.

Thanks,
_\- James_

**Comment by Trojaner** [comment]
Thank you for the bug report.
I will check this as soon as possible.

**Comment by James76931** [comment]
Thanks! :smile:

**Comment by Trojaner** [comment]
Please  try it with /rpos 1 and /rpos 2 (notice the whitespace)
