### ISSUE TITLE
Testers Thread

### ISSUE THREAD

**Issue by Trojaner** [Trojaner25/Rocket-Regions#5]
A thread for tests, so we can eliminiate bugs before this plugin gets released.

**Comment by flightcoin** [comment]
How would we go by compiling this plugin?

**Comment by flightcoin** [comment]
Nevermind, scratch what I said, I'll figure it out and test it out and create a new issue.

**Comment by CapnBio** [comment]
Looks like the plugin is running okay, I am going to run some tests tonight. See what exactly will happen if we run commands.

**Comment by Trojaner** [comment]
Do you think its stable enough for a release?

Do all flags work with no problems?
Is /sredefine <region> [params] still broken (does the region still gets deleted?)
Do circle & rectangle type safezones work with no problems?
Thanks for helping me

**Comment by CapnBio** [comment]
I see no errors, seems like it's working perfectly. I think it's good for release.

**Comment by CapnBio** [comment]
I believe you have done a very great job in all honesty. Thank you for making this plugin.

**Comment by Trojaner** [comment]
Thanks. I'm going to release it.
