### ISSUE TITLE
noequipweapon error spam

### ISSUE THREAD

**Issue by sharkbound** [Trojaner25/Rocket-Regions#50]
So i have a safezone on my server with noequipweapon flag on my server, then i started getting this spam in console 
https://gyazo.com/1c01407fd926e5dd9a6476d71ae23d78

Edit: It doesnt seem to be happening anymore. Not sure why it was happening
Edit 2: still happens sometimes
Edit 3: now im getting this https://gyazo.com/0fa10f8cf1a4b85fb7967445faa8a317
Edit 4: apears im getting a new error spam now https://gyazo.com/57efbeed8d1678215ac97d6196e7010d
Edit 5: now im getting this casting error spam even on novehiclesusage and noequip. appears this error can happen on any 'limiting' flag

**Comment by Trojaner** [comment]
Thanks for the report. I will look into this.

**Comment by Trojaner** [comment]
This seems to happen on all boolean type flags (on / off - true / false types).
Have you edited the config manually by any chance?

**Comment by sharkbound** [comment]
i did some but the times i did was to stop the error spam in console from the flags

**Comment by sharkbound** [comment]
also just some more info i found about the error spam is that it only seems to start the error spam if you have a bool flag enabled them you restart the server

**Comment by Trojaner** [comment]
Ok thanks
