### ISSUE TITLE
Godmode not working in regions

### ISSUE THREAD

**Issue by Realitea** [Trojaner25/Rocket-Regions#56]
/rflag name god on/true/1 is broken, no matter which element is used to enable it. Regions will tell me that it's enabled but it isn't.

After some more testing, it seems as though for anyone but admin god mode is enabled, even if it states ALL

**Comment by thomasreichmann** [comment]
After doing /rocket reload regions, /rocket load regions and /rocket unload regions I manged to have godmode on the safezone but after he left de safezone the godmode continued on him.

**Comment by jserodio** [comment]
I can confirm it's not working yet
