### ISSUE TITLE
Method not found: 'SDG.Unturned.StructureData.get_point' Error spam

### ISSUE THREAD

**Issue by sharkbound** [Trojaner25/Rocket-Regions#60]
its spamming this constantly in console on my server 
 MissingMethodException: Method not found: 'SDG.Unturned.StructureData.get_point'. - RocketRegions.RegionsPlugin.Update ()

**Comment by NaeemKhan14** [comment]
Having the same issue after the new update.

**Comment by Trojaner** [comment]
Fixed
