### ISSUE TITLE
Flags NoLeave and NoEnter

### ISSUE THREAD

**Issue by Railgun69** [Trojaner25/Rocket-Regions#7]
i've been testing the plugin on my server and both those flags dont work
i had my friend come into the server and try to enter and leave the area and he still can
not being an admin and not being on the same steam group

**Comment by Trojaner** [comment]
ok, will look into that

**Comment by Railgun69** [comment]
i forgot to add some info, to get to the safezone i created my friend had to swim

also i'll add a sugestion to the plugin, can you add a permission for certain groups to be able to bypass safezones ? that would be awesome

**Comment by Trojaner** [comment]
Fixed.
