### ISSUE TITLE
problem with rectangle in kent raceway

### ISSUE THREAD

**Issue by RJ1002** [Trojaner25/Rocket-Regions#78]
when I was trying to make a rptown in kent raceway it does not make a rectangle.

**Comment by Trojaner** [comment]
Problems wıth rectangles are already known, please use circular regions instead

**Comment by RJ1002** [comment]
when will you fix it

**Comment by Trojaner** [comment]
can sadly not give any ETA

**Comment by RJ1002** [comment]
can you give me estment
