### ISSUE TITLE
Player Crash

### ISSUE THREAD

**Issue by mra00** [Trojaner25/Rocket-Regions#8]
When I uploaded this plugin to my server, it removed everyone's stuff. I don't know if it wiped the player files clean or if it just didn't allow the server to connect to them, but it caused my server to go back a week to the last uncorrupted player files that I had. And the plugin didn't work at all either.

**Comment by Trojaner** [comment]
It currently doesnt even load, so there is no way that it deleted anything.

**Comment by mra00** [comment]
It doesn't allow for the players in-game to connect to the player file, so they spawn in naked. It then saves their player file as having nothing, so it essentially does delete player files.
