### ISSUE TITLE
For Group ALL always

### ISSUE THREAD

**Issue by ImNotSpectre** [Trojaner25/Rocket-Regions#81]
When If type: /rflag NoLeave true -g default" it say "Flag has been set to: true for Group ALL!"

Help pls

**Comment by Trojaner** [comment]
The flag groups are different than rocket groups. They are region based groups.

Supported groups are: members, nonmembers, owners, all (and probably some other)

You can add members with /rmember add <region> <player> and owners with /rowner add <region> <owner>.
