### ISSUE TITLE
Plugin wont download

### ISSUE THREAD

**Issue by Silverr12** [Trojaner25/Rocket-Regions#99]
placing the unityenginecoremodule.dll into plugins and running the server doesnt download any of the files, is there a link anywhere to the already downloaded/loaded file?

**Comment by Trojaner** [comment]
I dont know what you are trying to do.
First, the UnityEngine.CoreModule.dll is part of Unturned and must not be copied anywhere.
Secondly, this plugin is not downloading any files.

**Comment by Silverr12** [comment]
That is very strange because downloading via rocket harbour just gives me a zipped file with unityenginecoremodule.dll

**Comment by Trojaner** [comment]
You can download from here
https://github.com/Trojaner/Rocket-Regions/releases
